### ISSUE TITLE
Play button sometimes shows as paused

### ISSUE THREAD

**Issue by elliotjarnit** [ciderapp/Remote-iOS-BugTracker#3]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Remote-iOS-BugTracker/issues) for a bug report that matches the one I want to file, without success.

### Build Details

2.1 (3)

### Cider Version

Cider 2.0.3

### Describe the Bug

Sometimes the play button will show as paused even though the playback bar goes up and the song is playing.

### Steps to Reproduce

N/A

**Comment by ai9-** [comment]
was able to trigger this bug a minute ago. 
not able to reliably reproduce, got it after skipping a song.
